version: 2
updates:
  # For Gradle, update dependencies and plugins to the latest non-major version
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "scalar-labs/scalardb"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "software.amazon.awssdk:*"
        update-types: [ "version-update:semver-patch" ]
    groups:
      "Update dependencies":
        patterns:
          - "*"
#    groups:
  # For GitHub Actions workflows, update all actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "scalar-labs/scalardb"
    groups:
      "Update actions on branch (master)":
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "scalar-labs/scalardb"
    target-branch: "3"
    groups:
      "Update actions on branch (3)":
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "scalar-labs/scalardb"
    target-branch: "3.13"
    groups:
      "Update actions on branch (3.13)":
        patterns:
          - "*"