version: 2
updates:
  # For Gradle, update dependencies and plugins to the latest non-major version
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "scalar-labs/scalardb"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "software.amazon.awssdk:*"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "org.junit.jupiter:junit-jupiter-engine"
      - dependency-name: "com.oracle.database.jdbc"
  # For GitHub Actions workflows, update all actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "scalar-labs/scalardb"
