# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  ghcr:
    type: docker-registry
    url: https://ghcr.io
    username: ${{secrets.CR_USER}}
    password: ${{secrets.CR_PASSWORD}}
    replaces-base: true
updates:
  - package-ecosystem: "docker"
    directory: "/schema-loader/"
    registries:
      - ghcr
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "scalar-labs/jre8"
  - package-ecosystem: "docker"
    directory: "/server/"
    registries:
      - ghcr
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "scalar-labs/jre8"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "scalar-labs/jre8"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
