# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  ghcr:
    type: docker-registry
    url: https://ghcr.io
    username: ${{secrets.CR_USER}}
    password: ${{secrets.CR_PASSWORD}}
    replaces-base: true
updates:
  # For the Schema Loader Docker image, only update the scalar-labs/jre8 container
  - package-ecosystem: "docker"
    directory: "/schema-loader/"
    registries:
      - ghcr
    schedule:
      interval: "weekly"
    reviewers:
      - "scalar-labs/scalardb"
    allow:
      - dependency-name: "scalar-labs/jre8"
  # For the Server Docker image, only update the scalar-labs/jre8 container
  - package-ecosystem: "docker"
    directory: "/server/"
    registries:
      - ghcr
    schedule:
      interval: "weekly"
    reviewers:
      - "scalar-labs/scalardb"
    allow:
      - dependency-name: "scalar-labs/jre8"
  # For Gradle, update dependencies and plugins to the latest non-major version
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "scalar-labs/scalardb"
    allow:
      # Allow updates for Lodash
      - dependency-name: "software.amazon.awssdk:*"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "software.amazon.awssdk:*"
        update-types: [ "version-update:semver-patch" ]
  # For GitHub Actions workflows, update all actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "scalar-labs/scalardb"
