name: Auto-PR

on:
  pull_request:
    branches:
      - master
      - "[0-9]+"
      - "[0-9]+.[0-9]+"
    types:
      - closed

jobs:
  if_merged:
    uses: torch3333/scalardb/.github/workflows/auto-pr-reusable.yaml@master
    with:
      project_base_name: "ScalarDB fork"
      default_branch_name: "master"
      secrets: inherit
